apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    tier: webserver
  template:
    metadata:
      name: nginx
      labels:
        tier: webserver
    spec:
      containers:
      - name: nginx
        image: nginx
